services:
  postgres:
    ports:
        - 5432:5432
    container_name: neo_quiz_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_DB: neo_quiz_db
      POSTGRES_PASSWORD: admin
  neo_quiz:
    container_name: neo_quiz
    image: neo_quiz
    ports:
      - 9090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/neo_quiz_db
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres